### ISSUE TITLE
Please update

### ISSUE THREAD

**Issue by napokhte** [Fusl/intrace#23]
Error: The delayMs option was removed from express-rate-limit v3.

Also I can see mtr.sh is resolving domains but you haven't updated it here.

**Comment by Fusl** [comment]
Repo will be brought up to date with the currently running live version on mtr.sh in the next few days

**Comment by Fusl** [comment]
Code base has been updated with the live version from https://mtr.sh/, update of express-rate-limit to v3 and other dependencies will be tracked in #25.
