### ISSUE TITLE
Latam Testers

### ISSUE THREAD

**Issue by kleper** [Fusl/intrace#24]
Hello,

Can I provide free servers all over South America for testing, just in exchange for maybe some advertising, are you interested? 
I can provide, Colombia, Argentina, Peru, Chile, Brazil for now.
Stay tuned.
Thank you.

**Comment by Fusl** [comment]
Hi,

thanks for your offer. Mind reaching out to me directly at fusl@meo.ws or through other ways you can find at https://meo.ws/ ?
