### ISSUE TITLE
I can't select a probe(s), the probe is not available

### ISSUE THREAD

**Issue by procnix** [Fusl/intrace#34]
issue in selecting probe(s) , when I click on it still cannot select it. I don't understand what needs to be added, please tell me.

**Comment by Fusl** [comment]
Is this on a self-hosted instance? If you're trying to click on a probe but the interface doesn't allow you to select it, the probe is marked as offline. intrace v1 uses SSH to connect to probes so make sure SSH from the server running intrace is working correctly.

**Comment by procnix** [comment]
@Fusl, After I generated and added the public rsa key to the server where the probe is located, everything worked. In my project it was required, not only to create ed25519, but also RSA. The question is closed.
